language: python
cache: pip
python:
- "3.6"
sudo: required

install:
- pip install -r requirements.txt

before_script:
  - sudo chown -R $USER:$USER /root
  - psql -c 'create database qs_db;' -U postgres

script:
- coverage run --source=app/api/ -m pytest app/tests/v2  && coverage report -m

after_success:
- coveralls
